name: Python scripts tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/**'

jobs:
  test-scripts:
    name: Run tests for python scripts
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: python -m pip install pytest cryptography ecdsa intelhex
      - name: Run tests
        run: python -m pytest scripts
